### ISSUE TITLE
Turn this codebase into an NPM package

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/ACS_Assist#1]
**Description**
In order to start downloading other node modules and using them, we will need to have this code base be an NPM package

Here is some good documentation around creating an NPM package: https://docs.npmjs.com/creating-node-js-modules

**Acceptance criteria**

- [x] This repository contains a `package.json` file which contains information about this package

**Comment by saidah-neves** [comment]
1- Clone your repo locally
2- Navigate into the that repo via the command line and run npm init
3- Push the new code up to your repository

**Comment by Steven-Gassert** [comment]
closing this issue as complete
