### ISSUE TITLE
Be able to run this package as a command line tool

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/ACS_Assist#2]
**Description**
In order to run this package as a command line tool, we will need to configure our `package.json` correctly. See a good blog article on this here: https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e

**Acceptance criteria**

- [ ] As Steven, I look at the `Readme.md` file and I am able to install this package and run it as a command line tool. For now, running this package from the command line should just print our "Hello world"

**Comment by saidah-neves** [comment]
1- Configure the `package.json `correctly as per instructions above
2- Update the README.md file with instructions on how to install this package and run it as a command line tool

**Push the Changes**
1- Checkout a new branch `git checkout -b turn_into_cli`
2- Add your changes to a new branch `git add .`
3-Commit your changes to a new branch `git commit -m "Add existing file"`
4- Push up that branch `git push origin turn_into_cli`
5- Open a pull request
6- Follow instructions on README file

**Comment by Steven-Gassert** [comment]
Closing this as complete
