### ISSUE TITLE
Create an instance of Watson Discovery

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/ACS_Assist#6]
#### Description
In order to query Watson Discovery, we'll want to create a fresh instance of Discovery which will hold our ticket information. We can start by having our Watson Discovery instance under @saidah-neves 's account

#### Acceptance criteria

- [x] @saidah-neves has an instance discovery in her cloud.ibm.com account

**Comment by saidah-neves** [comment]
Discovery Instance created under my cloud.ibm.com account. Instance named ACS_Assist

**Comment by Steven-Gassert** [comment]
Closing this as complete
