### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/ACS_Assist#8]
### Description
Update the README so that anyone can execute this code from the command line

### Acceptance criteria

- [ ] As Mamoon, I can follow along with the README and run the `ACS_Assist` package on the command line

**Comment by saidah-neves** [comment]
@Steven-Gassert just to clarify this task. Are you referring to update the README file to execute the code for AddDocs? The ACS_Assist package mentioned above threw me off a bit

**Comment by Steven-Gassert** [comment]
@saidah-neves Yup that's correct as someone reading your README I'll want to know

1. How to clone your repo
2. Any installation steps I'll need to run (installing node modules) refer back to https://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm

**Comment by saidah-neves** [comment]
- See ReadMe file for new updates
- Mamoon and Steve should be able to follow along with the README and execute the code for AddDocs

**Comment by saidah-neves** [comment]
Completed
